### ISSUE TITLE
License issue

### ISSUE THREAD

**Issue by lkjell** [dark/dropbox-filesystem-fix#3]
You write that "This is based on code posted by one user of the forums (link, link to gist)."
However in [1] the license is MIT not GPL.

In particular MIT states: 

"The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software."

[1] https://github.com/dimaryaz/dropbox_ext4/blob/master/LICENSE

**Comment by dark** [comment]
Thanks for the note.
This repository, however, is not a fork of the repository you mentioned.

This code was initially derived from the gist that is linked in the readme, that has no attached license. When I modified that code to create the initial version of this repository, I chose to license it under GPLv3+.

**Comment by lkjell** [comment]
Whether it is a fork or not is irrelevant. The relevant part is that it is derived from a work by another author. Even if the author has not specified specifically the license in the gist the author still holds the copyright. The author has now specifically set a license, thus your work which is a derivative of the original work must comply with that license. Please change your license to MIT unless you have permission from the original author to use GPL in your derivative work.

**Comment by dark** [comment]
I disagree with your interpretation. I will keep the code licensed under GPL.

**Comment by lkjell** [comment]
What is your opinion @dimaryaz that @dark is using your work but depriving other from the license that you have specified?

**Comment by dimaryaz** [comment]
To be honest, I don't really care in this particular case. It's like 10 lines of code; I was considering releasing it as public domain, anyway.

**Comment by sanmai** [comment]
MIT code can be dual-licensed under GPL, so this is not even a problem. MIT license permits that.
