### ISSUE TITLE
Not working on dropbox-lnx.x86_64-62.3.93

### ISSUE THREAD

**Issue by lachesis** [dark/dropbox-filesystem-fix#4]
Just as I say, this version of Dropbox seems to see through the smoke-screen of latest master.

"So your file continue to sync, sign in to your Dropbox account and move Dropbox to a supported file system."
```
$ LD_PRELOAD=/usr/local/lib/libdropbox_fs_fix.so ./detect-ext4.o
success: It appears like we're on ext4.
$ ./detect-ext4.o
failure: Different filesystem type dete
![2018-11-07-104738_530x97_scrot](https://user-images.githubusercontent.com/347481/48153297-bc6dcc80-e27a-11e8-9a08-2ebcc0f49640.png)
cted.
$ LD_PRELOAD=/usr/local/lib/libdropbox_fs_fix.so $HOME/.dropbox-dist/dropboxd
<dropbox early boot logging spew, nothing useful or different from normal run>
```

**Comment by lachesis** [comment]
![2018-11-07-104738_530x97_scrot](https://user-images.githubusercontent.com/347481/48153368-e32c0300-e27a-11e8-943b-bb355251fe3a.png)

**Comment by sanmai** [comment]
I can confirm this issue.

**Comment by dark** [comment]
Dropbox did not update to that version for me yet - I am still at `dropbox-lnx.x86_64-61.4.95`. I suppose the rollout is gradual.

**Comment by lachesis** [comment]
You can grab any version of dropbox by URL hacking the download links. My version can be fetched at:
https://clientupdates.dropboxstatic.com/dbx-releng/client/dropbox-lnx.x86_64-62.3.93.tar.gz

**Comment by lachesis** [comment]
I am not sure if this is the problem, but it looks like this version of Dropbox reads from /etc/mtab:
```
openat(AT_FDCWD, "/etc/mtab", O_RDONLY|O_CLOEXEC) = 89
fstat(89, {st_mode=S_IFREG|0444, st_size=0, ...}) = 0
read(89, "proc /proc proc rw,nosuid,nodev,"..., 1024) = 1024
read(89, "noexec,relatime,perf_event 0 0\nc"..., 1024) = 1024
read(89, "ze=2M 0 0\ndebugfs /sys/kernel/de"..., 1024) = 701
read(89, "", 1024)                      = 0
close(89)                               = 0
```

**Comment by dark** [comment]
Sorta. It looks like the FS listing is derived from `/proc/filesystems` instead.
Pushing a fix now.

For the record, it looks like `chmod -R a-w "${HOME}/.dropbox-dist/"` was enough to prevent the client from updating to the newest version.

**Comment by lachesis** [comment]
Blocking auto-update will work for a while, but Dropbox now does forced rolling deprecation, so eventually your version of the client will be blocked and your sync will break. If you run headless and don't watch for this, you may not notice and might lose files you think are synced. Not that I have any experience with that or anything... :)

**Comment by lachesis** [comment]
Can confirm that the new patch seems to work for me, at least for now. Thanks!
