### ISSUE TITLE
make error on Archlinux

### ISSUE THREAD

**Issue by InvisibleRasta** [dark/dropbox-filesystem-fix#5]
% make
gcc -shared -fPIC -o libdropbox_fs_fix.so libdropbox_fs_fix.c -ldl
libdropbox_fs_fix.c: In function ‘statfs64’:
libdropbox_fs_fix.c:61:7: warning: ‘strncat’ specified bound 4 equals source length [-Wstringop-overflow=]
       strncat(canary_path, CANARY_FILE_PREFIX, strlen(CANARY_FILE_PREFIX));

**Comment by dark** [comment]
Thanks for the report!
I believe gcc-8 is being a little bit too pedantic here, but ok. This was fixed by #6.
