### ISSUE TITLE
Trivial startup script, symlink OK

### ISSUE THREAD

**Issue by fortran77** [dark/dropbox-filesystem-fix#8]
I made a symlink in `/usr/local/bin/` pointing to `dropbox_start.py` and it didn't work because that script doesn't trace the path of symlinks to locate itself.

So I ended up creating a tiny bash script to start Dropbox. I can symlink to it and it still works, because it contains a semi--hardcoded pathname. The script assumes that the `dropbox` command is available and that ~ contains no white space.

    -- cut here --
    #! /bin/bash

    L=~/Dropbox/dropbox-filesystem-fix/libdropbox_fs_fix.so
    test -x $L || { echo "error: not found $L" ; exit 1 ; }
    LD_PRELOAD=$L dropbox start
    -- cut here --

**Comment by dark** [comment]
> I made a symlink in /usr/local/bin/ pointing to dropbox_start.py and it didn't work because that script doesn't trace the path of symlinks to locate itself.

That's odd, since these lines do exactly that:
```
    lib_dir = os.path.dirname(os.path.realpath(__file__))
    lib_path = os.path.join(lib_dir, "libdropbox_fs_fix.so")
```

I tried to run the script via a symlink and it worked for me.

**Comment by fortran77** [comment]
I'll investigate further and report back soon.

**Comment by fortran77** [comment]
I am not able to reproduce the problem, though I could have sworn that I did encounter it. Maybe I just misinterpreted something on the screen. Sorry about the false alarm.

**Comment by dark** [comment]
No problem!
